pub const VOICE: &str = "Fred";

pub const SAMPLES: [&str; 35] = [
    "The cat is sleeping on the couch.",
    "I love eating pizza on Fridays.",
    "My favorite color is bright red.",
    "Can we play football in the park?",
    "The sun is shining very brightly today.",
    "My dog loves to play fetch.",
    "We are going to the zoo tomorrow.",
    "The teacher is reading a storybook.",
    "My little sister is only four years old.",
    "The ice cream truck is coming.",
    "I lost my favorite toy bear.",
    "The butterfly has colorful wings.",
    "I have two pet goldfish at home.",
    "My mom bakes the best cookies.",
    "The rainbow has seven different colors.",
    "Dad is washing the blue car.",
    "The big, yellow bus is late today.",
    "The moon shines brightly at night.",
    "We made a sandcastle at the beach.",
    "I like to climb trees in the park.",
    "The green frog jumps into the pond.",
    "My birthday is in the month of June.",
    "I can ride my bicycle very fast.",
    "The baby bird is learning to fly.",
    "I saw a shooting star last night.",
    "We are growing tomatoes in our garden.",
    "My best friend lives next door.",
    "The elephant at the zoo is very big.",
    "I like to eat apples and bananas.",
    "We saw a funny clown at the circus.",
    "The little duck is swimming in the lake.",
    "Grandma tells the best bedtime stories.",
    "The tall tree has lots of leaves.",
    "I love to draw pictures with crayons.",
    "My brother and I built a treehouse.",
];
