pub const VOICE: &str = "Mónica";

pub const SAMPLES: [&str; 35] = [
    "El gato está durmiendo en el sofá.",
    "Me encanta comer pizza los viernes.",
    "Mi color favorito es el rojo brillante.",
    "¿Podemos jugar al fútbol en el parque?",
    "El sol brilla muy fuerte hoy.",
    "A mi perro le encanta jugar a buscar.",
    "Vamos al zoo mañana.",
    "La maestra está leyendo un libro de cuentos.",
    "Mi hermana pequeña solo tiene cuatro años.",
    "El camión de helados está llegando.",
    "He perdido mi juguete favorito, un oso.",
    "La mariposa tiene alas coloridas.",
    "Tengo dos peces dorados en casa.",
    "Mi mamá hace las mejores galletas.",
    "El arco iris tiene siete colores diferentes.",
    "Papá está lavando el coche azul.",
    "El gran autobús amarillo llega tarde hoy.",
    "La luna brilla intensamente por la noche.",
    "Hicimos un castillo de arena en la playa.",
    "Me gusta trepar a los árboles en el parque.",
    "La rana verde salta al estanque.",
    "Mi cumpleaños es en el mes de junio.",
    "Puedo montar mi bicicleta muy rápido.",
    "El pájaro bebé está aprendiendo a volar.",
    "Vi una estrella fugaz anoche.",
    "Estamos cultivando tomates en nuestro jardín.",
    "Mi mejor amigo vive al lado.",
    "El elefante del zoo es muy grande.",
    "Me gusta comer manzanas y plátanos.",
    "Vimos a un payaso gracioso en el circo.",
    "El patito está nadando en el lago.",
    "La abuela cuenta las mejores historias antes de dormir.",
    "El árbol alto tiene muchas hojas.",
    "Me encanta dibujar con crayones.",
    "Mi hermano y yo construimos una casa en el árbol.",
];
