pub const VOICE: &str = "Alva";

pub const SAMPLES: [&str; 35] = [
    "Katten sover på soffan.",
    "Jag älskar att äta pizza på fredagar.",
    "Min favoritfärg är lysande röd.",
    "Kan vi spela fotboll i parken?",
    "Solen skiner mycket starkt idag.",
    "Min hund älskar att leka hämta.",
    "Vi ska gå till djurparken imorgon.",
    "Läraren läser en saga.",
    "Min lillasyster är bara fyra år gammal.",
    "Glassbilen kommer.",
    "Jag har tappat bort min favoritleksak, en björn.",
    "Fjärilen har färgglada vingar.",
    "Jag har två guldfiskar hemma.",
    "Min mamma bakar de bästa kakorna.",
    "Regnbågen har sju olika färger.",
    "Pappa tvättar den blå bilen.",
    "Den stora, gula bussen är sen idag.",
    "Månen lyser starkt på natten.",
    "Vi byggde ett sandslott på stranden.",
    "Jag gillar att klättra i träd i parken.",
    "Den gröna grodan hoppar in i dammen.",
    "Min födelsedag är i juni.",
    "Jag kan cykla mycket snabbt.",
    "Babyfågeln lär sig att flyga.",
    "Jag såg en stjärna falla i natt.",
    "Vi odlar tomater i vår trädgård.",
    "Min bästa vän bor intill.",
    "Elefanten på djurparken är väldigt stor.",
    "Jag tycker om att äta äpplen och bananer.",
    "Vi såg en rolig clown på cirkusen.",
    "Den lilla ankan simmar i sjön.",
    "Mormor berättar de bästa godnattsagorna.",
    "Det höga trädet har många blad.",
    "Jag älskar att rita bilder med kritor.",
    "Min bror och jag byggde ett trädhus.",
];
